### ISSUE TITLE
typo on readme

### ISSUE THREAD

**Issue by nmaxcom** [GalacticJS/GalacticJS#35]
> Example
> 
> First make sure you have TypeScript installed and **expermentalDecorators** is set to true in your tsconfig.json.
> 
> tsconfig.json
> 
> {
>   "compilerOptions": {
>     "module": "commonjs",
>     "target": "es6",
>     "**experimentalDecorators**": true
>   }
> }

**Comment by samvv** [comment]
Hi, thanks for noticing. I will push an update soon with lots of improvements and will fix it then.
